version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    ports:
      - "3000:3000"
