version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app-service

  app-service:
    build: ./api
    environment:
      - DB_ROOT_PASS=${DB_ROOT_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SERVER=${DB_SERVER}
    ports:
      - "3000:3000"
    depends_on:
      - db-service

  db-service:
    build: ./db
    environment:
      - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
